// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKDydowKJmpndjBl93n4pYRH-73MW9bNg',
    appId: '1:998087118432:web:6d001583f694619d39bd05',
    messagingSenderId: '998087118432',
    projectId: 'online-shop-e1128',
    authDomain: 'online-shop-e1128.firebaseapp.com',
    databaseURL: 'https://online-shop-e1128-default-rtdb.firebaseio.com',
    storageBucket: 'online-shop-e1128.appspot.com',
    measurementId: 'G-YMM7P1JHG9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkVPQcAxHeStffLQHGMCe4oW59OgJPqeg',
    appId: '1:998087118432:android:1e092f8a7326669739bd05',
    messagingSenderId: '998087118432',
    projectId: 'online-shop-e1128',
    databaseURL: 'https://online-shop-e1128-default-rtdb.firebaseio.com',
    storageBucket: 'online-shop-e1128.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa7VVbahOPQ3iLmYzu5QOwK1uqK2noRvs',
    appId: '1:998087118432:ios:299142a4f181a3a239bd05',
    messagingSenderId: '998087118432',
    projectId: 'online-shop-e1128',
    databaseURL: 'https://online-shop-e1128-default-rtdb.firebaseio.com',
    storageBucket: 'online-shop-e1128.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCa7VVbahOPQ3iLmYzu5QOwK1uqK2noRvs',
    appId: '1:998087118432:ios:299142a4f181a3a239bd05',
    messagingSenderId: '998087118432',
    projectId: 'online-shop-e1128',
    databaseURL: 'https://online-shop-e1128-default-rtdb.firebaseio.com',
    storageBucket: 'online-shop-e1128.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKDydowKJmpndjBl93n4pYRH-73MW9bNg',
    appId: '1:998087118432:web:c0ef980c19cc8ce439bd05',
    messagingSenderId: '998087118432',
    projectId: 'online-shop-e1128',
    authDomain: 'online-shop-e1128.firebaseapp.com',
    databaseURL: 'https://online-shop-e1128-default-rtdb.firebaseio.com',
    storageBucket: 'online-shop-e1128.appspot.com',
    measurementId: 'G-T8GHMW7CY3',
  );
}
